In [4]:
contoh = "latihan.txt"
file1 = open (contoh, "r")

In [5]:
file1.name

'latihan.txt'

In [6]:
file1.mode

'r'

In [7]:
FileContent = file1.read()
FileContent

'aku suci'

In [8]:
print(FileContent)

aku suci


In [9]:
type(FileContent)

str

In [10]:
file1.close()

In [12]:
with open(contoh, "r") as file1:
    FileContent = file1.read()
    print(FileContent)

Freda Nur Wahyuda
Peserta DTS 2020
DATA SCIENCE


In [13]:
file1.closed

True

In [14]:
print(FileContent)

Freda Nur Wahyuda
Peserta DTS 2020
DATA SCIENCE


In [16]:
with open(contoh, "r") as file1:
    print(file1.read(4))

Fred


In [17]:
with open(contoh, "r") as file1:
    print(file1.read(4))
    print(file1.read(4))
    print(file1.read(7))
    print(file1.read(15))

Fred
a Nu
r Wahyu
da
Peserta DTS 


In [18]:
with open(contoh, "r") as file1:
    print(file1.read(16))
    print(file1.read(5))
    print(file1.read(9))

Freda Nur Wahyud
a
Pes
erta DTS 


In [19]:
with open(contoh, "r") as file1:
    print("first line: " + file1.readline())

first line: Freda Nur Wahyuda



In [20]:
with open(contoh,"r") as file1:
        i = 0;
        for line in file1:
            print("Iteration", str(i), ": ", line)
            i = i + 1;

Iteration 0 :  Freda Nur Wahyuda

Iteration 1 :  Peserta DTS 2020

Iteration 2 :  DATA SCIENCE


In [21]:
with open(contoh, "r") as file1:
    FileasList = file1.readlines()

In [22]:
FileasList[0]

'Freda Nur Wahyuda\n'

In [24]:
FileasList[1]

'Peserta DTS 2020\n'

In [23]:
FileasList[2]

'DATA SCIENCE'

In [26]:
with open('latihan.txt', 'w') as writefile:
    writefile.write("Ini baris baru")

In [32]:
with open('latihan.txt','r') as testwritefile:
    print(testwritefile.read())

Ini baris baru


In [34]:
with open('latihan.txt', 'w') as writefile:
    writefile.write("Baris ke 2\n")
    writefile.write("Baris ke 3\n")

In [35]:
with open('latihan.txt','r') as testwritefile:
    print(testwritefile.read())

Baris ke 2
Baris ke 3



In [38]:
with open('latihan.txt', 'a') as testwritefile:
        testwritefile.write("Ini penambahan dengan append\n")

In [40]:
with open('latihan.txt','r') as testwritefile:
    print(testwritefile.read())

Baris ke 2
Baris ke 3
This is line C
Ini penambahan dengan append



In [43]:
Lines = ["List yang akan ditambahkan A\n", "Line B\n", "line C\n"]
Lines

['List yang akan ditambahkan A\n', 'Line B\n', 'line C\n']

In [45]:
with open('latihan.txt', 'w') as writefile:
    for line in Lines:
        print(line)
        writefile.write(line)

List yang akan ditambahkan A

Line B

line C



In [46]:
with open('latihan.txt','r') as testwritefile:
    print(testwritefile.read())

List yang akan ditambahkan A
Line B
line C



In [47]:
with open('latihan.txt', 'a') as testwritefile:
    testwritefile.write("penambahan dengan append 2\n")

In [48]:
with open('latihan.txt','r') as testwritefile:
    print(testwritefile.read())

List yang akan ditambahkan A
Line B
line C
penambahan dengan append 2



In [49]:
with open('latihan.txt','r') as readfile:
    with open('latihan2.txt','w') as writefile:
          for line in readfile:
                writefile.write(line)

In [52]:
with open('latihan2.txt','r') as testwritefile:
    print(testwritefile.read())

List yang akan ditambahkan A
Line B
line C
penambahan dengan append 2



In [14]:
a = ["0", 1, "dua", "3", 4]

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

type (a)

a[0]: 0
a[1]: 1
a[2]: dua
a[3]: 3
a[4]: 4


list

In [15]:
import numpy as np
b = np.array([0, 1, 2, 3, 4])
b
type (b)

numpy.ndarray

In [17]:
b.dtype

dtype('int32')

In [39]:
c = np.array([20, 1, 22, 13, 4])
c

array([20,  1, 22, 13,  4])

In [40]:
c[0] = 88
c[4] = 0
c


array([88,  1, 22, 13,  0])

In [42]:
d = c[1:4]
d

array([ 1, 22, 13])

In [43]:
acak = [1, 2, 3]
e = c[acak]
e

array([ 1, 22, 13])

In [45]:
c [acak] = 100000
c

array([    88, 100000, 100000, 100000,      0])

In [50]:
f = np.array([0, 1, 2, 3, 4])
print (f)
print (f.size)
print (f.ndim)
print (f.shape)

[0 1 2 3 4]
5
1
(5,)


In [59]:
g = np.array([1, -1, 1, -1])
print (g)
print (g.mean())
print (g.max())
print (g.min())


[ 1 -1  1 -1]
0.0
1
-1


In [66]:
u = np.array([2, 6])
v = np.array([3, 4])
z = u + v
z1 = u*v
print (z)
print (z1)
print (np.dot(u, v))

[ 5 10]
[ 6 24]
30


In [67]:
h = np.array([1, 2, 3, -1]) 
h+1

array([2, 3, 4, 0])

In [84]:
i= [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
i

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [95]:
I = np.array(i)
print (I)
print (I.ndim)
print (I.size)
print (I.shape)
print (type(I))
print (I[1, 2])
print (I[1] [2])
print (I[0][0:2])
print (I[1:2, 2])

[[11 12 13]
 [21 22 23]
 [31 32 33]]
2
9
(3, 3)
<class 'numpy.ndarray'>
23
23
[11 12]
[23]


In [103]:
x = np.array([[2, 4], [4, 2]]) 
y = np.array([[4, 6], [6, 4]]) 
w = x+y
w2 = x*y
w3 = np.dot(x,y)
print (w)
print (w2)
print (w3)
w.T

[[ 6 10]
 [10  6]]
[[ 8 24]
 [24  8]]
[[32 28]
 [28 32]]


array([[ 6, 10],
       [10,  6]])